netty:
  port: 7877

judger:
  judgePath: /home/qraffa/purple/judge
  dataPath: /home/qraffa/purple/data
  errorPath: /home/qraffa/purple/err.out
  logPath: /home/qraffa/purple/judger.log
  judgeSO: /home/qraffa/github/Judger/output/libjudger.so
  uid: 1000
  gid: 1000
  owner: qraffa
  group: qraffa